ngo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from ngoman import views as main

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^$', main.dashboard),
    url(r'^people/$', main.peopleview),
    url(r'^prog/$', main.programs),
    url(r'^ajax/$', main.ajaxproc),
    url(r'^ajaxrpt/$', main.ajaxprocrpt),
    url(r'^ngoadmin/$', main.ngoadmin),
    url(r'^reports/$', main.reports),
    url(r'^addperson/(?P<person>\d+)?/?$', main.addperson),
    url(r'^viewperson/(?P<person>\d+)?/?$', main.viewperson),
    url(r'^adduser/(?P<user>\d+)?/?$', main.adduser),
    url(r'^docs/(?P<person>\d+)/$', main.documents),
    url(r'^attendance/(?P<prog>\d+)?/?$', main.attendanceops),
    url(r'^manatt/(?P<person>\d+)?/?$', main.manatt),
    url(r'^search/', include('haystack.urls')),
    url(r'^changepass/(?P<user>\d+)?/?$', main.changepass),
    url(r'^getattendance/(?P<prog>\d+)?/?$', main.getattendance),
    url(r'^viewreports/?$', main.viewreports),
]

ngoman/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import force_bytes
from django.contrib.postgres.fields import JSONField

from django.db import models
from datetime import date
import datetime
from django.contrib.auth.models import User
import os

def get_upload_path(instance, filename):
    return "static/documents/%s/%s" % (instance.owner.id, filename)

class AgeLimitManager(models.Manager):
    def get_queryset(self, agelimit, gtlt):
        limitdate = datetime.datetime.now() - datetime.timedelta(days=agelimit*365)
        if gtlt == 0:
            return super(AgeLimitManager, self).get_queryset().filter(birthdate__lte=limitdate)
        else:
            return super(AgeLimitManager, self).get_queryset().filter(birthdate__gte=limitdate)

class AdultManager(models.Manager):
    def get_queryset(self):
        adultbdate = datetime.datetime.now() - datetime.timedelta(days=18*365)
        return super(AdultManager, self).get_queryset().filter(birthdate__lte=adultbdate)

class ChildManager(models.Manager):
    def get_queryset(self):
        childbdate = datetime.datetime.now() - datetime.timedelta(days=18*365)
        return super(ChildManager, self).get_queryset().filter(birthdate__gt=childbdate)

# Create your models here.
'''
class isttown(models.Model):
    tname = models.CharField()
'''

class country(models.Model):
    ccode = models.CharField(max_length=2, blank=True)
    cname_tr = models.CharField(max_length=255, blank=True)
    cname_en = models.CharField(max_length=255, blank=True)
    class Meta:
        ordering = ["cname_tr"]

    def __str__(self):
        return self.cname_tr.encode('utf8')

class programmes(models.Model):
    pname = models.CharField(max_length=255, help_text='Programme name', unique=True)
    distprod = models.CharField(max_length=255, help_text='Distributed good', blank=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return u"/prog/?q=%s" % self.pname

    def __str__(self):
        return self.pname.encode('utf8')

    class Meta:
        verbose_name_plural = 'programmes'

class proggroups(models.Model):
    gname = models.CharField(max_length=10, help_text='Group name')
    programme = models.ForeignKey(programmes)

    def __str__(self):
        return self.gname


class locality(models.Model):
    townid = models.IntegerField()
    lname = models.CharField(max_length=255)

    def __str__(self):
        tmpstr = u'%s' % self.lname
        return tmpstr.encode('utf-8')

class people(models.Model):
    TOWN_CHOICES = (
            ('1', 'Adalar'),
            ('2', u'Bakırköy'),
            ('3', u'Beşiktaş'),
            ('4', 'Beykoz'),
            ('5', u'Beyoğlu'),
            ('6', u'Çatalca'),
            ('7', u'Eyüp'),
            ('8', 'Fatih'),
            ('9', u'Gaziosmanpaşa'),
            ('10', u'Kadıköy'),
            ('11', 'Kartal'),
            ('12', u'Sarıyer'),
            ('13', 'Silivri'),
            ('14', u'Şile'),
            ('15', u'Şişli'),
            ('16', u'Üsküdar'),
            ('17', 'Zeytinburnu'),
            ('18', u'Büyükçekmece'),
            ('19', u'Kağıthane'),
            ('20', u'Küçükçekmece'),
            ('21', 'Pendik'),
            ('22', u'Ümraniye'),
            ('23', 'Bayrampaşa'),
            ('24', u'Avcılar'),
            ('25', u'Bağcılar'),
            ('26', u'Bahçelievler'),
            ('27', u'Güngören'),
            ('28', 'Maltepe'),
            ('29', 'Sultanbeyli'),
            ('30', 'Tuzla'),
            ('31', 'Esenler'),
            ('32', u'Arnavutköy'),
            ('33', u'Ataşehir'),
            ('34', u'Başakşehir'),
            ('35', u'Beylikdüzü'),
            ('36', 'Çekmeköy'),
            ('37', 'Esenyurt'),
            ('38', 'Sancaktepe'),
            ('39', 'Sultangazi'),
    )
    PERSON_STATUS = (
            ('A', 'Aktif'),
            ('D', 'Deaktif(Arşiv)'),
            ('W', 'Beklemede'),
            ('H', 'Askıda'),
    )
    GENDER_CHOICES = (
            ('M', 'Male'),
            ('F', 'Female'),
    )
    MARITIAL_CHOICES = (
            ('M', 'Evli'),
            ('U', 'Bekar'),
            ('W', 'Dul'),
    )
    EDU_CHOICES = (
            ('P', 'İlkokul'),
            ('S', 'Ortaokul'),
            ('H', 'Lise'),
            ('U', 'Üniversite'),
            ('M', 'Master'),
            ('D', 'PhD'),
    )

    fname = models.CharField(max_length=255)
    sname = models.CharField(max_length=255)
    country = models.ForeignKey(country)
    children = models.ManyToManyField('self', blank=True, symmetrical=False)
    phonenum = models.CharField(max_length=20, null=True)
    idnum = models.CharField(max_length=100, null=True)
    notes = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    birthdate = models.DateField(help_text='Date of birth MM/DD/YYYY')
    programmes = models.ManyToManyField(programmes, blank=True, symmetrical=False)
    archived = models.CharField(max_length=1, choices=PERSON_STATUS, default='A')
    regdate = models.DateField()
    updated = models.DateTimeField(auto_now=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='F')
    maritialstatus = models.CharField(max_length=1, choices=MARITIAL_CHOICES, default='M')
    olddata = models.TextField(null=True, blank=True)
    deactivedate = models.DateTimeField(null=True, blank=True)
    arrivaldate = models.DateField(null=True, blank=True)
    education = models.CharField(max_length=1, choices=EDU_CHOICES, default='P')
    docscomplete = models.BooleanField(default=False)
    speaktr = models.BooleanField(default=False)
    town = models.IntegerField(choices=TOWN_CHOICES, blank=True, null=True)
    locality = models.ForeignKey(locality, on_delete=models.SET_NULL, null=True, blank=True)

    def age(self):
        '''Calculate the person's age in years.'''
        end = date.today()
        years = end.year - self.birthdate.year
        if end.month and self.birthdate.month:
            if end.month < self.birthdate.month or (end.month == self.birthdate.month and end.day and self.birthdate.day and end.day < self.birthdate.day):
                years -= 1
        return years

    def fullname(self):
        return u'%s %s' % (self.fname, self.sname)

    def get_absolute_url(self):
        return u"/people/?q=%s" % (self.fullname())

    class Meta:
        verbose_name_plural = 'people'

    def __unicode__(self):
        return unicode(self.fullname())

    def __str__(self):
        return self.fullname()

    objects = models.Manager()
    adult_objects = AdultManager()
    child_objects = ChildManager()
    agefilter = AgeLimitManager()

class doctype(models.Model):
    dtname = models.CharField(max_length=255)

    def __str__(self):
        return self.dtname

class document(models.Model):
    filename = models.FileField(upload_to=get_upload_path)
    doctype = models.ForeignKey(doctype)
    owner = models.ForeignKey(people)
    uploaddate = models.DateTimeField(auto_now_add=True, blank=True)
    description = models.CharField(max_length=255, null=True)

    def get_filename(self):
        return os.path.basename(self.filename.name)

    def __str__(self):
        return '%s - %s - %s' % (self.filename, self.doctype, self.owner.fullname())

class log(models.Model):
    user = models.ForeignKey(User)
    event = models.CharField(max_length=255)
    eventtime = models.DateTimeField(auto_now_add=True, blank=True)
    ipaddr = models.GenericIPAddressField(unpack_ipv4=True)

class attendance(models.Model):
    people = JSONField(default='{}')
    programme = models.ForeignKey(programmes)
    attdate = models.DateField(auto_now_add=True, blank=True)

    class Meta:
        unique_together = ('programme', 'attdate')


class orgdoc(models.Model):
    filename = models.FileField(upload_to="static/orgdocs/")
    description = models.CharField(max_length=255, null=True)
    uploaddate = models.DateTimeField(auto_now_add=True, blank=True)

    def get_filename(self):
        return os.path.basename(self.filename.name)

    def __str__(self):
        return '%s - %s' % (self.filename, self.description)

ngoman/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from ngoman.models import people, document, orgdoc, locality
from django.contrib.auth.models import User


class personForm(forms.ModelForm):
    class Meta:
        model = people
        fields = ['fname', 'sname', 'gender', 'docscomplete', 'country', 'maritialstatus', 'regdate', 'education', 'children', 'phonenum', 'idnum', 'address', 'locality', 'town', 'birthdate', 'programmes', 'notes', 'olddata', 'arrivaldate', 'speaktr', 'archived']
        labels = {
            "fname": "Ad",
            "sname": "Soyad",
            "phonenum": "Telefon",
            "idnum": "Kimlik No",
            "gender": "Cinsiyet",
            "docscomplete": u"Belgeleri Tamam mı?",
            "country": "Ülke",
            "maritialstatus": "Medeni Hali",
            "education": "Tahsil",
            "children": u"Çocukları",
            "address": "Adres",
            "locality": "Mahalle",
            "town": "İlçe",
            "birthdate": u"Doğum Tarihi",
            "programmes": "Üye Olduğu Programlar",
            "notes": "Notlar",
            "olddata": "Eski Bilgiler",
            "arrivaldate": u"Ülkeye Varış Tarihi",
            "regdate": u"Kayıt Tarihi",
            "speaktr": u"Türkçe biliyor",
            "archived": u"Kayıt Durumu",
        }

    def __init__(self, *args, **kwargs):
        super(personForm, self).__init__(*args, **kwargs)
        self.fields['locality'].queryset = locality.objects.none()

class OrgDocsForm(forms.ModelForm):
    class Meta:
        model = orgdoc
        fields = ['filename', 'description']

class OrgDocsUpdateForm(forms.ModelForm):
    filename = forms.FileField(required=False)
    class Meta:
        model = orgdoc
        fields = ['filename', 'description']

class PersonalDocsUpdateForm(forms.ModelForm):
    filename = forms.FileField(required=False)

    class Meta:
        model = document
        fields = ['filename', 'doctype', 'description']

class PersonalDocsForm(forms.ModelForm):
    myid = forms.IntegerField(widget=forms.HiddenInput)

    class Meta:
        model = document
        fields = ['filename', 'doctype', 'description', 'myid']

class AdminUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class UserUpdateForm(forms.ModelForm):
    #password = forms.CharField(required=False, widget=forms.PasswordInput)
    #password_confirm = forms.CharField(required=False, widget=forms.PasswordInput())

    class Meta:
        model = User
        # Add all the fields you want a user to change
        fields = ('first_name', 'last_name', 'username', 'email', 'is_superuser')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirm = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'is_superuser', 'password')

templates/addperson.html
{% extends 'main.html' %}
{% load bootstrap4 %}

{% block title %}Yeni {{type}}{% endblock %}

{% block innerpages %}
<div class="card ">
    <div class="card-header">
        <h4>{{type}} {% if edit %}değiştir{% else %}ekle{% endif %}</h4>
    </div>
    <div class="card-body">
        <form id="addform" method="POST" role='form'>
            {% csrf_token %}
            {% bootstrap_form myform %}
            {% buttons %}
            <button class="btn btn-success" type="submit">Save</button>
            <button class="btn btn-danger" type="cancel" id="addpersoncancel">Cancel</button>
            {% endbuttons %}
        </form>
        <div class="pull-right">
        </div>
    </div>
</div>
<script>
{% if type == 'Sığınmacı' %}
$(document).ready(function() {
    $('#id_town').change(function() {
        var townId = $(this).val();
        $.ajax({
            url: '/ajax/',
            type: 'POST',
            data: {
                'action': 'loadlocality',
                'town': townId,
            },
            success: function(data) {
                $('#id_locality').html(data)
            }
        });

    });

	$("#addpersoncancel").click(function(e) {
		e.preventDefault();
		window.history.back();
	});

	$('#id_arrivaldate').datepicker({
		format: 'dd/mm/yyyy',
		autoclose: 'true',
		todayHighlight: 'true',
	});
	$('#id_regdate').datepicker({
		format: 'dd/mm/yyyy',
		autoclose: 'true',
		todayHighlight: 'true',
	});

	$('#id_birthdate').datepicker({
		format: 'dd/mm/yyyy',
		autoclose: 'true',
		todayHighlight: 'true',
		changeMonth: true,
		changeYear: true
	});
});

{% endif %}
</script>
{% endblock %}

templates/documents.html
{% extends 'main.html' %}
{% load bootstrap4 %}

{% block title %}Manage Documents{% endblock %}

{% block innerpages %}
<div class="modal fade" id="adddoc" tabindex="-1" role="dialog" aria-labelledby="adddoc">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addNewLabel">{{myname}} için belge yükleme<b id='psubpname'></b></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form method="POST" role='form' id="uploadform" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form myform %}
                </form>
            </div>
            <div class="modal-footer">
                {% buttons %}
                <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
                <button class="btn btn-success" id="uploaddoc">Yükle</button>
                {% endbuttons %}
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4><i>{{myname}}</i> icin belgeler</h4>
    </div>
    <div class="card-body">
        <button type="submit" id="newdoc" class="btn btn-success">Yeni belge ekle</button>
        <p></p>
        <table class="table table-condensed" id="doctable">
            <thead><th>Dosya</th><th>Yükleme Tarihi</th><th>Dosya Tipi</th><th>Açıklama</th><th>İşlemler</th><th>id</th></thead>
            <tbody>
            {% for i in mydocs %}
            <tr><td><a href="/{{i.filename}}" target="_blank">{{ i.get_filename }}</a></td><td>{{i.uploaddate|date:"Y-m-d H:i:s"}}</td><td>{{i.doctype.dtname}}</td><td>{{i.description}}</td><td><div class="btn-group" role="group" ><button class="btn btn-sm btn-warning edit text-light"><i class="fas fa-edit"></i></button><button class="btn btn-sm btn-danger delete"><i class="far fa-trash-alt"></i></button></div></td><td>{{i.id}}</td></tr>
            {% endfor %}
            </tbody>
        </table>
        <p></p>
    </div>
</div>
<script>

$(document).ready(function() {
{% if edit %}
    $('#adddoc').modal('show');
{% endif %}

{% if request.GET.adddocs == 'true' %}
    toastr.success('Operation Successful');
{% else %}
    {% if request.GET.adddocs == 'false' %}
        toastr.success('Islem Basarisiz');
    {% endif %}
{% endif %}
});

var doctable = $('#doctable').DataTable({
    "searching": false,
    "paging": false,
    "info": false,
    "columnDefs": [{
        "targets": 4,
        "orderable": false,
    },
    {
        "targets": 3,
        "orderable": false,
    },
    {
        "targets": 5,
        "orderable": false,
        "visible": false
    }],
});
$('#doctable tbody').on('click', 'button', function() {
    var myparent = $(this).parents('tr');
    var rowData = doctable.row(myparent).data();
    if ($(this).hasClass('edit')) {
        $('#adddoc').modal('show');
        var tmpval = $('#id_doctype option').filter(function () { return $(this).html() == rowData[2]; }).val();
        $('#id_doctype').val(tmpval);
        $('#id_description').val(rowData[3]);
        $('#id_myid').val(rowData[5]);
        $('#id_filename').prop('required', false);
    } else if ($(this).hasClass('delete')) {
        $.ajax({
            url: '/ajax/',
            type: 'POST',
            data: { action: 'deletedoc', 'docid': rowData[5] },
            success: function(data) {
                if (data.result == 0) {
                    toastr.success('Dokuman silindi');
                    doctable.row(myparent).remove().draw();
                } else {
                    toastr.error('Hata olustu');
                }
            },
            error: function() {
                toastr.error('Hata olustu');
            }
        });
    }
});

$('#newdoc').click(function() {
    $('#id_myid').val('');
    $('#id_filename').prop('required', true);
    $('#adddoc').modal('show');
});

$('#uploaddoc').click(function() {
    $('#uploadform').submit();
});
</script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <div class="col-sm-8 col-md-8 offset-md-2 offset-md-2">
        <div class="card">
            <div class="card-header">
                <h2>Login</h2>
            </div>
            <div class="card-body">
                <form method="post" role='form'>
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button class="btn btn-success" type="submit">Login</button>
                {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/showattendance.html
{% extends 'main.html' %}
{% block title %}Yoklama sayfasi{% endblock %}

{% block innerpages %}
<h3>{{myprog.pname}} için yoklama durumu</h3>
<div><span class="font-weight-bold">Semboller:</span> <i class="fas fa-check text-success"></i> Var <i class="fas fa-times text-danger"></i> Yok <i class="fas fa-suitcase text-primary"></i> Programda henüz yok/Veri yok</div>

<table class="table" id="atttable">
    <thead>
        <tr><th>Ad soyad</th><th>Kimlik no</th>{% for i in mydates %}<th><div class="small text-nowrap">{{i}}</div></th>{% endfor %}</tr>
    </thead>
    <tbody>
        {% for i in myret %}
        <tr><td>{{i.fullname}}</td><td>{{i.idnum}}</td>{% for j in i.mydates %}<td>{% ifequal j 't' %}<i class="fas fa-check text-success"></i>{% else %}{% ifequal j 'f' %}<i class="fas fa-times text-danger"></i>{% else %}<i class="fas fa-suitcase text-primary"></i>{% endifequal %}{% endifequal %}</td>{% endfor %}</tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/viewperson.html
{% extends 'main.html' %}

{% block title %}Person Info{% endblock %}
{% block innerpages %}
<div class="row">
    <div class="col-md-5 ml-auto">
        <p class=" text-info">Güncelleme: {{person.updated|date:"Y-m-d H:i:s"}} </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 mx-auto toppad" id="printarea">
        {% if person.archived == 'A' %}
        <div class="card card-info">
        {% else %}
            {% if person.archived == 'D' %}
        <div class="card card-danger">
            {% else %}
                {% if person.archived == 'W' %}
        <div class="card card-success">
                {% else %}
                    {% if person.archived == 'H' %}
        <div class="card card-warning">
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
            <div class="card-header">
                <h3 class="card-title">{{person.fname|title}} {{person.sname|title}} {% if person.archived == 'D' %}(Deaktif){% else %}{% if person.archived == 'W' %}(Beklemede){% else %}{% if person.archived == 'H' %}(Askida){% endif %}{% endif %}{% endif %}</h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> </div>
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Geldiği ülke:</td>
                        <td><a href="https://www.google.com/maps/search/?api=1&zoom=1&query={{person.country}}" target=_blank>{{person.country}}</a></td>
                      </tr>
                      <tr>
                          <td>Kimlik no:</td>
                        <td>{{person.idnum}}</td>
                      </tr>
                      <tr>
                          <td>Yaş</td>
                          <td>{{person.age}}</td>
                      </tr>
                      <tr>
                        <td>Doğum tarihi:</td>
                        <td>{{person.birthdate|date:"Y-m-d"}}</td>
                      </tr>
                    <tr>
                        <td>Cinsiyet:</td>
                        <td>{{person.gender}}</td>
                      </tr>
                    <tr>
                        <td>Kayıt tarihi:</td>
                        <td>{{person.regdate|date:"Y-m-d"}}</td>
                    </tr>
                    <tr>
                        <td>Eğitim durumu:</td>
                        <td>{{person.get_education_display}}</td>
                    </tr>
                        <tr>
                        <td>Ev adresi:</td>
                        <td>{{person.address}}</td>
                      </tr>
                      <tr>
                        <td>Telefon no:</td>
                        <td>{{person.phonenum}}</td>
                      </tr>
                      {% if person.children.all.count > 0 %}
                      <tr>
                          <td>Çocukları:</td>
                          <td>
                              {% for i in person.children.all %}
                              <a href="/viewperson/{{i.id}}/" target="_blank">{{i}}</a><br>
                              {% endfor %}
                          </td>
                      </tr>
                      {% endif %}
                      {% if parents %}
                      <tr>
                          <td>Ebeveynleri:</td>
                          <td>
                              {% for i in parents %}
                              <a href="/viewperson/{{i.id}}/" target="_blank">{{i}}</a><br>
                              {% endfor %}
                          </td>
                      </tr>
                      {% endif %}
                      <tr>
                          <td>Notlar</td>
                          <td>{{person.notes}}</td>
                      </tr>
                      {% if person.olddata != ''%}
                      <tr>
                          <td>Eski Bilgiler</td>
                          <td>{{person.olddata}}</td>
                      </tr>
                      {% endif %}
                      <tr>
                          <td>Türkiye'ye varış tarihi</td>
                          <td>{{person.arrivaldate}}</td>
                      </tr>
                      <tr>
                          <td>Üye olduğu programlar</td>
                          <td>{% for i in person.programmes.all %}{{i}}<br>{% endfor %}</td>
                      </tr>
                      <tr class="no-print">
                          <td>Documents</td>
                          <td><button class="btn btn-sm {% if person.docscomplete %}btn-success">Tamam{% else %}btn-danger">Tamam Degil{% endif %} 
                                  <i class="fas fa-{% if person.docscomplete %}check{% else %}times{% endif %}"></i>
                              </button>
                          </td>
                          </tr>
                      </tbody>
                  </table>
                  <!--
                  </div>
                  -->
                  <button class="btn btn-primary no-print" id="showdocs">Sığınmacı belgeleri</button>
                </div>
              </div>
            </div>
             <div class="card-footer no-print">
                <button data-original-title="Print this page" id="print" type="button" class="btn btn-primary">Yazdır <i class="fa fa-print"></i></button>
                <span class="float-right">
                    <a href="/addperson/{{person.id}}/" role="button" class="btn btn-warning">Düzenle <i class="fas fa-edit"></i></a>
                    <a id="toggleuser" role="button" class="btn btn-danger"><i class="far fa-times-circle"></i><i class="fas fa-check-circle"></i></a>
                </span>
            </div>
            
          </div>
        </div>
      </div>
      <script>
        $(document).ready(function() {
            {% if person.archived == 'A' %}
                $('#toggleuser').children('i.fa-check-circle').hide();
                $('#toggleuser').children('i.fas-times-circle').show();
                $('#toggleuser').removeClass('btn-success');
                $('#toggleuser').addClass('btn-danger');
                /*
                $('.card-header').removeClass('bg-danger');
                $('.card-header').addClass('bg-info');
                */
            {% else %}
                $('#toggleuser').children('i.fa-check-circle').show();
                $('#toggleuser').children('i.fas-times-circle').hide();
                $('#toggleuser').removeClass('btn-danger');
                $('#toggleuser').addClass('btn-success');
                /*
                $('.card-header').addClass('bg-danger');
                $('.card-header').removeClass('bg-info');
                */
            {% endif %}
        });

        $('#showdocs').click(function() {
            document.location.href = '/docs/{{person.id}}/';
        });

        $('#toggleuser').click(function() {
            if ($(this).hasClass('btn-danger')) {
                var myarchive = 1;
                var mymsg = ' deactivated';
            } else {
                var myarchive = 0;
                var mymsg = ' activated';
            }

            $.ajax({
                "url" : "/ajax/",
                "type": "POST",
                "data": { "action": "personarchive", "id": {{person.id}}, "archive": myarchive },
                "success": function(data) {
                    if (data.result == 0) {
                        toastr.success("{{person.fullname}} " + mymsg);
                        if (myarchive == 1) {
                            $('#toggleuser').children('i.fa-check-circle').show();
                            $('#toggleuser').children('i.fa-times-circle').hide();
                            $('#toggleuser').removeClass('btn-danger');
                            $('#toggleuser').addClass('btn-success');
                            $('.card-title').text("{{person.fname|title}} {{person.sname|title}} (Deaktif)");
                            $('.card-header').addClass('bg-danger');
                            $('.card-header').removeClass('bg-info');
                        } else {
                            $('#toggleuser').children('i.fa-check-circle').hide();
                            $('#toggleuser').children('i.fa-times-circle').show();
                            $('#toggleuser').removeClass('btn-success');
                            $('#toggleuser').addClass('btn-danger');
                            $('.card-title').text("{{person.fname|title}} {{person.sname|title}}");
                            $('.card-header').removeClass('bg-danger');
                            $('.card-header').addClass('bg-info');
                         }

                    } else {
                        toastr.error('Error!');
                    }
                }
            });
        });
        $('#print').click(function() {
            $('#printarea').print();
        });
      </script>
{% endblock %}